project:
  type: book

book:
  title: "smacof at 50"
  subtitle: "A Manual"  
  author: 
    - name: Jan de Leeuw
      orcid: 0000-0003-1420-1797
      email: jan@deleeuwpdx.net
      affiliation: 
        - name: University of California Los Angeles
          city: Los Angeles
          state: CA
          url: www.ucla.edu
      license: "CC0"  
  date: last-modified
  chapters:
    - index.qmd     
    - intro.qmd
    - basics.qmd
    - convergence.qmd
    - acceleration.qmd
    - metric.qmd
    - interval.qmd
    - notation.qmd

bibliography: 
  - total.bib
  - mypubs.bib


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    pdf-engine: lualatex
    include-in-header: 
      - preamble.tex
    mainfont: Times New Roman
    documentclass: scrbook
    
colorlinks: true
fontsize: 12pt
toc: true
toc-depth: 3
editor: source
papersize: letter
graphics: true
link-citations: true


